# Generated by Django 4.2.7 on 2023-12-11 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='image/')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('email', models.EmailField(max_length=20)),
                ('password', models.IntegerField(default=0)),
            ],
        ),
    ]
