# Generated by Django 4.2.7 on 2023-12-16 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_shop_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='email',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='password',
        ),
    ]
